/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Alexis
 */
public class FrmAgregarUsuario extends javax.swing.JFrame {

    private int idUsuario;
    private int sesion;
    /**
     * Creates new form FrmAgregarUsuario
     */
    public FrmAgregarUsuario() {
        initComponents();
        this.setLocationRelativeTo(null); 
         addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                FrmFactura frmFactura = new FrmFactura(idUsuario, sesion);
                frmFactura.setVisible(true);
                dispose();
            }
        });
    }
    
    public FrmAgregarUsuario(int id, int sesion) {
       
        initComponents();
        idUsuario = id;
        this.sesion = sesion;
        this.setLocationRelativeTo(null); 
         addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                FrmFactura frmFactura = new FrmFactura(idUsuario, sesion);
                frmFactura.setVisible(true);
                dispose();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_titulo = new javax.swing.JLabel();
        lb_tituloNombre = new javax.swing.JLabel();
        lb_tituloContrasenia = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        password_contrasenia = new javax.swing.JPasswordField();
        btn_salir = new javax.swing.JButton();
        btn_crear = new javax.swing.JButton();
        lb_confirmacion = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar usuario");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_titulo.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lb_titulo.setForeground(new java.awt.Color(255, 255, 255));
        lb_titulo.setText("Agregar usuario");
        getContentPane().add(lb_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, 48));

        lb_tituloNombre.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lb_tituloNombre.setText("Nombre de usuario");
        getContentPane().add(lb_tituloNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 105, -1, 33));

        lb_tituloContrasenia.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lb_tituloContrasenia.setText("contraseña");
        getContentPane().add(lb_tituloContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 157, -1, 35));

        txt_nombre.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txt_nombre.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        getContentPane().add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 104, 145, 35));

        password_contrasenia.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        password_contrasenia.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        password_contrasenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_contraseniaActionPerformed(evt);
            }
        });
        getContentPane().add(password_contrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 157, 145, 35));

        btn_salir.setBackground(new java.awt.Color(255, 102, 102));
        btn_salir.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btn_salir.setText("Salir");
        btn_salir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        getContentPane().add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 134, 39));

        btn_crear.setBackground(new java.awt.Color(153, 255, 153));
        btn_crear.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btn_crear.setText("Crear");
        btn_crear.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crearActionPerformed(evt);
            }
        });
        getContentPane().add(btn_crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 152, 39));

        lb_confirmacion.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        getContentPane().add(lb_confirmacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 281, 237, 42));

        jPanel1.setBackground(new java.awt.Color(105, 105, 105));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 80));

        jPanel2.setBackground(new java.awt.Color(226, 241, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 410, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void password_contraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_contraseniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password_contraseniaActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        FrmFactura frmFactura = new FrmFactura(idUsuario, sesion);
        frmFactura.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crearActionPerformed
         try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/bd_punto_de_ventas", "root", "");
            PreparedStatement pst = cn.prepareStatement("insert into usuarios values(?,?,?)");
                         
            pst.setString(1, "0");
            pst.setString(2, txt_nombre.getText().trim());
            pst.setString(3, password_contrasenia.getText().trim());
            pst.executeUpdate();
            
            txt_nombre.setText("");
            password_contrasenia.setText("");
            lb_confirmacion.setText("Registro exitoso!!!"); 
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "No se pudo tener acceso a la base de datos");
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Existe algun/algunos campos invalidos");
        }
    }//GEN-LAST:event_btn_crearActionPerformed
    
    public void mostarUsuario(){
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAgregarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAgregarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAgregarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAgregarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAgregarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_crear;
    private javax.swing.JButton btn_salir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lb_confirmacion;
    private javax.swing.JLabel lb_titulo;
    private javax.swing.JLabel lb_tituloContrasenia;
    private javax.swing.JLabel lb_tituloNombre;
    private javax.swing.JPasswordField password_contrasenia;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
}
