/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.*;
import javax.swing.JOptionPane;
import modelo.*;

/**
 *
 * @author Alexis
 */
public class FrmAgregarProducto extends javax.swing.JFrame {
    private int sesion;
    private int idFact;
    /**
     * Creates new form FrmProducto
     */
    public FrmAgregarProducto() {
        initComponents();
        comboBox_tipoContenido.getSelectedIndex();
        setLocationRelativeTo(null);
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                FrmFactura frmFactura = new FrmFactura(idFact, sesion);
                frmFactura.setVisible(true);
                dispose();
            }
        });
    }
    
    public FrmAgregarProducto(int id, int sesion) {
   
        initComponents();
        this.sesion = sesion;
        idFact = id;
        comboBox_tipoContenido.getSelectedIndex();
        setLocationRelativeTo(null);
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                FrmFactura frmFactura = new FrmFactura(idFact, sesion);
                frmFactura.setVisible(true);
                dispose();
            }
        }); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        txt_nombreProducto = new javax.swing.JTextField();
        btn_Agregar = new javax.swing.JButton();
        lb_cantidad = new javax.swing.JLabel();
        lb_nombreProducto = new javax.swing.JLabel();
        lb_titulo = new javax.swing.JLabel();
        txt_precio = new javax.swing.JTextField();
        lb_precio1 = new javax.swing.JLabel();
        lb_contenido = new javax.swing.JLabel();
        btn_Salir = new javax.swing.JButton();
        spinner_cantidad = new javax.swing.JSpinner();
        comboBox_tipoContenido = new javax.swing.JComboBox<>();
        spinner_tipoContenido = new javax.swing.JSpinner();
        panel_header = new javax.swing.JPanel();
        panel_body = new javax.swing.JPanel();
        lb_confirmacionRegistro = new javax.swing.JLabel();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregando Productos");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_nombreProducto.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txt_nombreProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreProductoActionPerformed(evt);
            }
        });
        getContentPane().add(txt_nombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 106, 225, 30));

        btn_Agregar.setBackground(new java.awt.Color(153, 255, 153));
        btn_Agregar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_Agregar.setText("Agregar");
        btn_Agregar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 170, 40));

        lb_cantidad.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lb_cantidad.setText("Cantidad");
        lb_cantidad.setPreferredSize(new java.awt.Dimension(62, 25));
        getContentPane().add(lb_cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 190, -1, -1));

        lb_nombreProducto.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lb_nombreProducto.setText("Nombre Producto");
        lb_nombreProducto.setPreferredSize(new java.awt.Dimension(123, 25));
        getContentPane().add(lb_nombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 111, -1, -1));

        lb_titulo.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lb_titulo.setForeground(new java.awt.Color(255, 255, 255));
        lb_titulo.setText("Agregando Producto");
        getContentPane().add(lb_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 13, -1, 64));

        txt_precio.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txt_precio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_precioActionPerformed(evt);
            }
        });
        getContentPane().add(txt_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 144, 225, 30));

        lb_precio1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lb_precio1.setText("Precio");
        lb_precio1.setPreferredSize(new java.awt.Dimension(45, 25));
        getContentPane().add(lb_precio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 149, -1, -1));

        lb_contenido.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lb_contenido.setText("Contenido");
        lb_contenido.setPreferredSize(new java.awt.Dimension(73, 25));
        getContentPane().add(lb_contenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 225, -1, -1));

        btn_Salir.setBackground(new java.awt.Color(255, 102, 102));
        btn_Salir.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_Salir.setText("Salir");
        btn_Salir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalirActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 270, 170, 40));

        spinner_cantidad.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        spinner_cantidad.setModel(new javax.swing.SpinnerNumberModel(0, 0, 99, 1));
        getContentPane().add(spinner_cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 182, 226, 30));

        comboBox_tipoContenido.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        comboBox_tipoContenido.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "g", "ml", "L", "Kg", "Pza/s" }));
        comboBox_tipoContenido.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        comboBox_tipoContenido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBox_tipoContenidoActionPerformed(evt);
            }
        });
        getContentPane().add(comboBox_tipoContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 225, 90, -1));

        spinner_tipoContenido.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        spinner_tipoContenido.setModel(new javax.swing.SpinnerNumberModel(1.0d, 1.0d, 999.0d, 1.0d));
        spinner_tipoContenido.setPreferredSize(new java.awt.Dimension(74, 25));
        getContentPane().add(spinner_tipoContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 223, 100, 30));

        panel_header.setBackground(new java.awt.Color(105, 105, 105));

        javax.swing.GroupLayout panel_headerLayout = new javax.swing.GroupLayout(panel_header);
        panel_header.setLayout(panel_headerLayout);
        panel_headerLayout.setHorizontalGroup(
            panel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );
        panel_headerLayout.setVerticalGroup(
            panel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        getContentPane().add(panel_header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 80));

        panel_body.setBackground(new java.awt.Color(226, 241, 255));

        lb_confirmacionRegistro.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        javax.swing.GroupLayout panel_bodyLayout = new javax.swing.GroupLayout(panel_body);
        panel_body.setLayout(panel_bodyLayout);
        panel_bodyLayout.setHorizontalGroup(
            panel_bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_bodyLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(lb_confirmacionRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );
        panel_bodyLayout.setVerticalGroup(
            panel_bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_bodyLayout.createSequentialGroup()
                .addContainerGap(240, Short.MAX_VALUE)
                .addComponent(lb_confirmacionRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        getContentPane().add(panel_body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 470, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nombreProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreProductoActionPerformed

    private void txt_precioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_precioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_precioActionPerformed

    private void btn_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AgregarActionPerformed
       
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/bd_punto_de_ventas", "root", "");
            PreparedStatement pst = cn.prepareStatement("insert into productos values(?,?,?,?,?)");
            
            if(Double.parseDouble(txt_precio.getText().trim()) > 0){              
            pst.setString(1, "0");
            pst.setString(2, txt_nombreProducto.getText().trim());
            pst.setString(3, txt_precio.getText().trim());
            pst.setString(4, spinner_cantidad.getValue().toString());
            //pst.setString(5, txt_contenido.getText().trim());
            pst.setString(5, ("" + spinner_tipoContenido.getValue().toString().trim() + " " + comboBox_tipoContenido.getSelectedItem().toString().trim()).trim());
            pst.executeUpdate();

            txt_nombreProducto.setText("");
            txt_precio.setText("");
            spinner_cantidad.setValue(0);
            //txt_contenido.setText("");
            spinner_tipoContenido.setValue(1);
            
            
            lb_confirmacionRegistro.setText("Registro exitoso!!!"); 
            }else{
                JOptionPane.showMessageDialog(null, "El precio debe ser mayor que cero");
            }

            
            
        } catch(SQLException e){
            JOptionPane.showMessageDialog(null, "No se pudo tener acceso a la base de datos");
        }catch(Exception e){ 
            JOptionPane.showMessageDialog(null, "Algun campo es erroneo");
        }
        
        
    }//GEN-LAST:event_btn_AgregarActionPerformed

    private void comboBox_tipoContenidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBox_tipoContenidoActionPerformed
        // TODO add your handling code here:
        String s = comboBox_tipoContenido.getSelectedItem().toString();
        System.out.println(s);
    }//GEN-LAST:event_comboBox_tipoContenidoActionPerformed

    private void btn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalirActionPerformed
        // TODO add your handling code here:
        FrmFactura frmFactura = new FrmFactura(idFact, sesion);
        frmFactura.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_SalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAgregarProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Agregar;
    private javax.swing.JButton btn_Salir;
    private javax.swing.JComboBox<String> comboBox_tipoContenido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lb_cantidad;
    private javax.swing.JLabel lb_confirmacionRegistro;
    private javax.swing.JLabel lb_contenido;
    private javax.swing.JLabel lb_nombreProducto;
    private javax.swing.JLabel lb_precio1;
    private javax.swing.JLabel lb_titulo;
    private javax.swing.JPanel panel_body;
    private javax.swing.JPanel panel_header;
    private javax.swing.JSpinner spinner_cantidad;
    private javax.swing.JSpinner spinner_tipoContenido;
    private javax.swing.JTextField txt_nombreProducto;
    private javax.swing.JTextField txt_precio;
    // End of variables declaration//GEN-END:variables
}
