/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;


/**
 *
 * @author Alexis
 */
public class FrmEliminarProducto extends javax.swing.JFrame {
    private int idFact;
    private int sesion;
    /**
     * Creates new form FrmEliminarProducto
     */
    public FrmEliminarProducto() {
        initComponents();
        this.setLocationRelativeTo(null); 
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                FrmFactura frmFactura = new FrmFactura(idFact, sesion);
                frmFactura.setVisible(true);
                dispose();
            }
        });
    }
    
    public FrmEliminarProducto(int id, int sesion) {
        
        initComponents();
        this.sesion = sesion;
        idFact = id;
        this.setLocationRelativeTo(null); 
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                FrmFactura frmFactura = new FrmFactura(idFact, sesion);
                frmFactura.setVisible(true);
                dispose();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_titulo = new javax.swing.JLabel();
        lb_idProdcuto = new javax.swing.JLabel();
        txt_idProducto = new javax.swing.JTextField();
        btn_salir = new javax.swing.JButton();
        btn_eliminarProducto = new javax.swing.JButton();
        lb_pantallaCarga = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lb_datosEncontrados = new javax.swing.JLabel();
        lb_idProdcuto1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_titulo.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lb_titulo.setForeground(new java.awt.Color(255, 255, 255));
        lb_titulo.setText("Eliminar Producto");
        getContentPane().add(lb_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 28, -1, -1));

        lb_idProdcuto.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lb_idProdcuto.setText("Datos encontrados");
        getContentPane().add(lb_idProdcuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 191, -1, 36));

        txt_idProducto.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txt_idProducto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_idProducto.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txt_idProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idProductoActionPerformed(evt);
            }
        });
        getContentPane().add(txt_idProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 136, 200, 37));

        btn_salir.setBackground(new java.awt.Color(255, 102, 102));
        btn_salir.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btn_salir.setText("Salir");
        btn_salir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        getContentPane().add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 303, 100, 37));

        btn_eliminarProducto.setBackground(new java.awt.Color(153, 255, 153));
        btn_eliminarProducto.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btn_eliminarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imegenes Proyecto/Eliminar basura muy pequeño.png"))); // NOI18N
        btn_eliminarProducto.setText("Eliminar");
        btn_eliminarProducto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_eliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarProductoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_eliminarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 303, 110, 37));
        getContentPane().add(lb_pantallaCarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 218, 46));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imegenes Proyecto/Buscar lupa muy pequenia.png"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 136, 42, 37));

        lb_datosEncontrados.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lb_datosEncontrados.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        getContentPane().add(lb_datosEncontrados, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 240, 254, 37));

        lb_idProdcuto1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lb_idProdcuto1.setText("Ingrese el ID del producto");
        getContentPane().add(lb_idProdcuto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 93, 208, 36));

        jPanel2.setBackground(new java.awt.Color(105, 105, 105));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, -1));

        jPanel3.setBackground(new java.awt.Color(226, 241, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 400, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        // TODO add your handling code here:
        FrmFactura frmFactura = new FrmFactura(idFact, sesion);
        frmFactura.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_eliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarProductoActionPerformed
        // TODO add your handling code here:
        
         try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/bd_punto_de_ventas", "root", "");
            PreparedStatement pst = cn.prepareStatement("delete from productos where ID = ?");
            
            pst.setString(1, txt_idProducto.getText().trim());

            pst.executeUpdate();
            this.txt_idProducto.setText("");
            lb_pantallaCarga.setText("Eliminacion del producto exitosa!!!");
                
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "No se pudo tener acceso a la base de datos");
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "El ID del producto es incorrecto");
        }
        
    }//GEN-LAST:event_btn_eliminarProductoActionPerformed

    private void txt_idProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idProductoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/bd_punto_de_ventas", "root", "");
            PreparedStatement pst = cn.prepareStatement("select * from productos where ID = ?");

            pst.setString(1, this.txt_idProducto.getText().trim());

            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                lb_datosEncontrados.setText("ID:  " + rs.getString("ID") + "      Nombre:  " + rs.getString("NombreProducto"));
            } else {
                lb_datosEncontrados.setText("Producto no encontrado!");
            }
        } catch(SQLException e){
            JOptionPane.showMessageDialog(null, "No se pudo tener acceso a la base de datos");
        } catch (Exception e) {
            lb_datosEncontrados.setText("Entrada de ID no valida");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEliminarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEliminarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEliminarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEliminarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEliminarProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_eliminarProducto;
    private javax.swing.JButton btn_salir;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lb_datosEncontrados;
    private javax.swing.JLabel lb_idProdcuto;
    private javax.swing.JLabel lb_idProdcuto1;
    private javax.swing.JLabel lb_pantallaCarga;
    private javax.swing.JLabel lb_titulo;
    private javax.swing.JTextField txt_idProducto;
    // End of variables declaration//GEN-END:variables
}
