/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Alexis
 */
public class FrmModificarUsuario extends javax.swing.JFrame {
    
    private int idUsuario;
    private int sesion;
    /**
     * Creates new form FrmModificarUsuario
     */
    public FrmModificarUsuario() {
        initComponents();
        this.setLocationRelativeTo(null);
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                FrmFactura frmFactura = new FrmFactura(idUsuario, sesion);
                frmFactura.setVisible(true);
                dispose();
            }
        });
    }
    
    public FrmModificarUsuario(int id, int sesion) {
      
        initComponents();
        this.setLocationRelativeTo(null);
        idUsuario = id;
        this.sesion = sesion;
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                FrmFactura frmFactura = new FrmFactura(idUsuario, sesion);
                frmFactura.setVisible(true);
                dispose();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_contrasenia = new javax.swing.JLabel();
        lb_pantallaConfirmacion = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        txt_contrasenia = new javax.swing.JTextField();
        lb_nombre = new javax.swing.JLabel();
        lb_nombre1 = new javax.swing.JLabel();
        btn_salir = new javax.swing.JButton();
        btn_modificar1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txt_idUsuario = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lb_titulo2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_contrasenia.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lb_contrasenia.setText("Contraseña");
        getContentPane().add(lb_contrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 207, -1, -1));

        lb_pantallaConfirmacion.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        getContentPane().add(lb_pantallaConfirmacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 305, 240, 39));

        txt_nombre.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txt_nombre.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txt_nombre.setPreferredSize(new java.awt.Dimension(8, 30));
        getContentPane().add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 146, 234, 40));

        txt_contrasenia.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txt_contrasenia.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        getContentPane().add(txt_contrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 199, 234, 40));

        lb_nombre.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lb_nombre.setText("Nombre de usuario");
        getContentPane().add(lb_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 154, -1, -1));

        lb_nombre1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lb_nombre1.setText("Ingrese el ID del usuario");
        getContentPane().add(lb_nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 106, -1, -1));

        btn_salir.setBackground(new java.awt.Color(255, 102, 102));
        btn_salir.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btn_salir.setText("Salir");
        btn_salir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        getContentPane().add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 252, 198, 40));

        btn_modificar1.setBackground(new java.awt.Color(153, 255, 153));
        btn_modificar1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btn_modificar1.setText("Modificar");
        btn_modificar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_modificar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_modificar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 252, 190, 40));

        jPanel2.setBackground(new java.awt.Color(254, 247, 176));

        txt_idUsuario.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txt_idUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_idUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txt_idUsuario.setPreferredSize(new java.awt.Dimension(8, 30));

        btn_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imegenes Proyecto/Buscar lupa muy pequenia.png"))); // NOI18N
        btn_buscar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(223, Short.MAX_VALUE)
                .addComponent(txt_idUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_idUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(238, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 520, 290));

        jPanel3.setBackground(new java.awt.Color(105, 105, 105));

        lb_titulo2.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lb_titulo2.setForeground(new java.awt.Color(255, 255, 255));
        lb_titulo2.setText("Modificar usuario");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(lb_titulo2)
                .addContainerGap(186, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(lb_titulo2)
                .addGap(23, 23, 23))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        // TODO add your handling code here:
        FrmFactura frmFactura = new FrmFactura(idUsuario, sesion);
        frmFactura.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_modificar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificar1ActionPerformed
         try {
           String ID = txt_idUsuario.getText().trim();
           Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/bd_punto_de_ventas", "root", "");
           PreparedStatement pst = cn.prepareStatement("update usuarios set usuario = ?, contrasenia = ? where ID = " + ID);
           pst.setString(1, (txt_nombre.getText().trim()));
           pst.setString(2, (txt_contrasenia.getText().trim()));
           pst.executeUpdate();
           lb_pantallaConfirmacion.setText("Modificación exitosa!");
        } catch(SQLException e){
            JOptionPane.showMessageDialog(null, "No se pudo tener acceso a la base de datos");
        }catch (Exception e) {
             lb_pantallaConfirmacion.setText("Algún campo no es válido!");
        }
    }//GEN-LAST:event_btn_modificar1ActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/bd_punto_de_ventas", "root", "");
            PreparedStatement pst = cn.prepareStatement("select * from usuarios where ID = ?");

            pst.setString(1, this.txt_idUsuario.getText().trim());

            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                
                txt_nombre.setText(rs.getString("usuario"));
                txt_contrasenia.setText(rs.getString("contrasenia"));
            } else {
                lb_pantallaConfirmacion.setText("Datos del producto no encontrados");
            }

        } catch(SQLException e){
            JOptionPane.showMessageDialog(null, "No se pudo tener acceso a la base de datos");
        }catch (Exception e) {
             lb_pantallaConfirmacion.setText("Entrada de ID np válida!");
        }
    }//GEN-LAST:event_btn_buscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmModificarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmModificarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmModificarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmModificarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmModificarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_modificar1;
    private javax.swing.JButton btn_salir;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lb_contrasenia;
    private javax.swing.JLabel lb_nombre;
    private javax.swing.JLabel lb_nombre1;
    private javax.swing.JLabel lb_pantallaConfirmacion;
    private javax.swing.JLabel lb_titulo2;
    private javax.swing.JTextField txt_contrasenia;
    private javax.swing.JTextField txt_idUsuario;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
}
