/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;
import modelo.ExcepcionValoresIncorrectos;

/**
 *
 * @author Alexis
 */
public class FrmModificarProducto extends javax.swing.JFrame {
    private int idUsuario;
    private int sesion;
    /**
     * Creates new form FrmModificarProducto
     */
    public FrmModificarProducto() {
        initComponents();
        this.setLocationRelativeTo(null);

        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                FrmFactura frmFactura = new FrmFactura(idUsuario, sesion);
                frmFactura.setVisible(true);
                dispose();
            }
        });
    }

    public FrmModificarProducto(int id, int sesion) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.sesion = sesion;
        this.idUsuario = id;
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                FrmFactura frmFactura = new FrmFactura(idUsuario, sesion);
                frmFactura.setVisible(true);
                dispose();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        panel_fondo1 = new javax.swing.JPanel();
        lb_idProducto2 = new javax.swing.JLabel();
        txt_idProducto = new javax.swing.JTextField();
        btn_buscarID = new javax.swing.JButton();
        lb_Nombre = new javax.swing.JLabel();
        lb_Precio = new javax.swing.JLabel();
        spinner_modificarCantidad = new javax.swing.JSpinner();
        spinner_modificarPrecio = new javax.swing.JSpinner();
        lb_Cantidad = new javax.swing.JLabel();
        btn_modificar1 = new javax.swing.JButton();
        btn_modificar2 = new javax.swing.JButton();
        lb_pantallaConfirmacion = new javax.swing.JLabel();
        txt_nombreProducto = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lb_titulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 102));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_fondo1.setBackground(new java.awt.Color(254, 247, 176));

        lb_idProducto2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lb_idProducto2.setText("Ingrese el ID del Producto");

        txt_idProducto.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txt_idProducto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_idProducto.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btn_buscarID.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btn_buscarID.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imegenes Proyecto/Buscar lupa muy pequenia.png"))); // NOI18N
        btn_buscarID.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_buscarID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarIDActionPerformed(evt);
            }
        });

        lb_Nombre.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lb_Nombre.setText("Nombre del producto");

        lb_Precio.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lb_Precio.setText("Precio");

        spinner_modificarCantidad.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        spinner_modificarCantidad.setModel(new javax.swing.SpinnerNumberModel(1, 0, 99, 1));
        spinner_modificarCantidad.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        spinner_modificarCantidad.setPreferredSize(new java.awt.Dimension(43, 35));

        spinner_modificarPrecio.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        spinner_modificarPrecio.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10000, 1));
        spinner_modificarPrecio.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        spinner_modificarPrecio.setPreferredSize(new java.awt.Dimension(87, 35));

        lb_Cantidad.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lb_Cantidad.setText("Cantidad");

        btn_modificar1.setBackground(new java.awt.Color(153, 255, 153));
        btn_modificar1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btn_modificar1.setText("Modificar");
        btn_modificar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_modificar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificar1ActionPerformed(evt);
            }
        });

        btn_modificar2.setBackground(new java.awt.Color(255, 102, 102));
        btn_modificar2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btn_modificar2.setText("Salir");
        btn_modificar2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_modificar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificar2ActionPerformed(evt);
            }
        });

        lb_pantallaConfirmacion.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        txt_nombreProducto.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txt_nombreProducto.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txt_nombreProducto.setPreferredSize(new java.awt.Dimension(8, 38));

        javax.swing.GroupLayout panel_fondo1Layout = new javax.swing.GroupLayout(panel_fondo1);
        panel_fondo1.setLayout(panel_fondo1Layout);
        panel_fondo1Layout.setHorizontalGroup(
            panel_fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_fondo1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(panel_fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_fondo1Layout.createSequentialGroup()
                        .addComponent(btn_modificar2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_modificar1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_fondo1Layout.createSequentialGroup()
                        .addComponent(lb_idProducto2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_idProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_buscarID, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_fondo1Layout.createSequentialGroup()
                        .addGroup(panel_fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_Nombre)
                            .addComponent(txt_nombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(panel_fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spinner_modificarPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_Precio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panel_fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_Cantidad)
                            .addComponent(spinner_modificarCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_fondo1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lb_pantallaConfirmacion, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        panel_fondo1Layout.setVerticalGroup(
            panel_fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_fondo1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panel_fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_buscarID, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lb_idProducto2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_idProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42)
                .addGroup(panel_fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_Nombre)
                    .addComponent(lb_Precio)
                    .addComponent(lb_Cantidad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinner_modificarPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinner_modificarCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_modificar2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_modificar1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_pantallaConfirmacion, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panel_fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 510, 280));

        jPanel2.setBackground(new java.awt.Color(105, 105, 105));

        lb_titulo.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lb_titulo.setForeground(new java.awt.Color(255, 255, 255));
        lb_titulo.setText("Modificar Producto");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(lb_titulo)
                .addContainerGap(157, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(lb_titulo)
                .addGap(23, 23, 23))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_modificar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificar1ActionPerformed
        /*
        try {
            String ID = txt_idProducto.getText().trim();
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/bd_punto_de_ventas", "root", "");
            PreparedStatement pst = cn.prepareStatement("update productos set NombreProducto = ?, Precio = ?, Cantidad = ? where ID = " + ID);
           
            if (txt_nombreProducto.getText() == "" || (((double) spinner_modificarPrecio.getValue()) < 0) || (((double) spinner_modificarCantidad.getValue()) < 0)) {
                 JOptionPane.showMessageDialog(null, "Llegue aqui");
                throw new ExcepcionValoresIncorrectos("Valores incorrectos");
                
            }
             
            pst.setString(1, txt_nombreProducto.getText().trim());
            pst.setString(2, ("" + spinner_modificarPrecio.getValue()).trim());
            pst.setString(3, ("" + spinner_modificarCantidad.getValue()).trim());
            pst.executeUpdate();

            JOptionPane.showMessageDialog(null, "Modificacion exitosa");
        } catch (ExcepcionValoresIncorrectos e) {
            JOptionPane.showMessageDialog(null, "Los valores son ingresados incorrectos");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "No se pudo tener acceso a la base de datos");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Existe un campo erroneo");
        }
        */
       
        try {
           String ID = txt_idProducto.getText().trim();
           Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/bd_punto_de_ventas", "root", "");
           PreparedStatement pst = cn.prepareStatement("update productos set NombreProducto = ?, Precio = ?, Cantidad = ? where ID = " + ID);

           pst.setString(1, txt_nombreProducto.getText().trim());
           pst.setString(2, ("" + spinner_modificarPrecio.getValue()).trim());
           pst.setString(3, ("" + spinner_modificarCantidad.getValue()).trim());
           pst.executeUpdate();
           
           JOptionPane.showMessageDialog(null, "Modificacion exitosa");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "No se pudo tener acceso a la base de datos");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Existe un campo erroneo");
        }
        
        
    }//GEN-LAST:event_btn_modificar1ActionPerformed

    private void btn_buscarIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarIDActionPerformed
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/bd_punto_de_ventas", "root", "");
            PreparedStatement pst = cn.prepareStatement("select * from productos where ID = ?");

            pst.setString(1, this.txt_idProducto.getText().trim());

            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                
                txt_nombreProducto.setText(rs.getString("NombreProducto"));
                spinner_modificarPrecio.setValue(Integer.parseInt(rs.getString("Precio")));
                spinner_modificarCantidad.setValue(Integer.parseInt(rs.getString("Cantidad")));
                
            } else {
                JOptionPane.showMessageDialog(null, "Producto no encontrado");
            }

        } catch(SQLException e){
            JOptionPane.showMessageDialog(null, "No se pudo tener acceso a la base de datos");
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Entrada de ID no valida");
        }
    }//GEN-LAST:event_btn_buscarIDActionPerformed

    private void btn_modificar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificar2ActionPerformed
        FrmFactura frmFactura = new FrmFactura(idUsuario, sesion);
        frmFactura.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_modificar2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmModificarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmModificarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmModificarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmModificarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmModificarProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscarID;
    private javax.swing.JButton btn_modificar1;
    private javax.swing.JButton btn_modificar2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel lb_Cantidad;
    private javax.swing.JLabel lb_Nombre;
    private javax.swing.JLabel lb_Precio;
    private javax.swing.JLabel lb_idProducto2;
    private javax.swing.JLabel lb_pantallaConfirmacion;
    private javax.swing.JLabel lb_titulo;
    private javax.swing.JPanel panel_fondo1;
    private javax.swing.JSpinner spinner_modificarCantidad;
    private javax.swing.JSpinner spinner_modificarPrecio;
    private javax.swing.JTextField txt_idProducto;
    private javax.swing.JTextField txt_nombreProducto;
    // End of variables declaration//GEN-END:variables
}
