/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Font;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import modelo.Producto;
import modelo.*;

/**
 *
 * @author Alexis
 */
public class FrmVisualizarProductos extends javax.swing.JFrame {
    
    private int idUsuario;
    private int sesion;
    
    ArrayList <Producto> listaProductosBase =  new ArrayList <Producto>();
    /**
     * Creates new form FrmVisualizarProductos
     */
    public FrmVisualizarProductos() {
        initComponents();
        this.setLocationRelativeTo(null); 
        recuperarBaseDeDatosProducto();
        tb_productos.getTableHeader().setFont(new Font("SansSerif", Font.BOLD, 18));
        inicializaTabla(tb_productos);
        
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                FrmFactura frmFactura = new FrmFactura(idUsuario, sesion);
                frmFactura.setVisible(true);
                dispose();
            }
        });
       
    }
    
    public FrmVisualizarProductos(int id, int sesion) {
       
        initComponents();
        idUsuario = id;
        this.sesion = sesion;
        this.setLocationRelativeTo(null); 
        recuperarBaseDeDatosProducto();
        tb_productos.getTableHeader().setFont(new Font("SansSerif", Font.BOLD, 18));
        inicializaTabla(tb_productos);
        
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                FrmFactura frmFactura = new FrmFactura(idUsuario, sesion);
                frmFactura.setVisible(true);
                dispose();
            }
        });
       
    }
    
    public void recuperarBaseDeDatosProducto() {
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/bd_punto_de_ventas", "root", "");
            PreparedStatement pst = cn.prepareStatement("SELECT * FROM productos");

            ResultSet rs = pst.executeQuery();
            
            while (rs.next()) {
                int idProducto = rs.getInt("ID");
                String nombre = rs.getString("NombreProducto");
                double precio = rs.getDouble("Precio");
                double cantidad = rs.getDouble("Cantidad");
                String tipoContenido = rs.getString("TipoContenido");
                Producto productos = new Producto(idProducto, nombre, precio, cantidad, tipoContenido);
                listaProductosBase.add(productos);
            }
           
        } catch(SQLException e){
            JOptionPane.showMessageDialog(null, "No se pudo tener acceso a la base de datos");
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Entrada de ID no valida");
        }
    }
   
    
    
    public void inicializaTabla(JTable tabla) {

        Vector<String> titulos = new Vector<String>();
        Vector<Vector<Object>> data = new Vector<Vector<Object>>();
        
        titulos.add("ID");
        titulos.add("Nombre");
        titulos.add("Precio");
        titulos.add("Cantidad");
        titulos.add("Tipo Cont.");
        
        for (int i = 0; i < listaProductosBase.size(); i++) {
            Vector<Object> row = new Vector<Object>();
            if (listaProductosBase.get(i) instanceof Producto) {
                Producto abarrotes = (Producto) listaProductosBase.get(i);
                row.add(abarrotes.getId());
                row.add(abarrotes.getNombre());
                row.add(abarrotes.getPrecio());
                row.add(abarrotes.getCantidad());
                row.add(abarrotes.getContenidoNeto());
            }
            data.add(row);
        }
        DefaultTableModel modelo = new DefaultTableModel(data, titulos);
        tabla.setModel(modelo);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_productos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lb_titulo2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(240, 230, 162));

        tb_productos.setBackground(new java.awt.Color(255, 255, 204));
        tb_productos.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tb_productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_productos.setAlignmentX(0.8F);
        tb_productos.setAlignmentY(0.8F);
        tb_productos.setRowHeight(20);
        jScrollPane1.setViewportView(tb_productos);
        if (tb_productos.getColumnModel().getColumnCount() > 0) {
            tb_productos.getColumnModel().getColumn(0).setHeaderValue("Title 1");
            tb_productos.getColumnModel().getColumn(1).setHeaderValue("Title 2");
            tb_productos.getColumnModel().getColumn(2).setHeaderValue("Title 3");
            tb_productos.getColumnModel().getColumn(3).setHeaderValue("Title 4");
        }

        jButton1.setBackground(new java.awt.Color(255, 137, 137));
        jButton1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButton1.setText("Salir");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 67, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 683, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 683, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 820, 350));

        jPanel3.setBackground(new java.awt.Color(105, 105, 105));

        lb_titulo2.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lb_titulo2.setForeground(new java.awt.Color(255, 255, 255));
        lb_titulo2.setText("Lista de productos");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(307, 307, 307)
                .addComponent(lb_titulo2)
                .addContainerGap(297, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(lb_titulo2)
                .addGap(23, 23, 23))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        FrmFactura frmFactura = new FrmFactura(idUsuario, sesion);
        frmFactura.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVisualizarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVisualizarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVisualizarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVisualizarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmVisualizarProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_titulo2;
    private javax.swing.JTable tb_productos;
    // End of variables declaration//GEN-END:variables
}
